### PR TITLE
Update to 01.00.29

### PR DESCRIPTION
**Pull request by mauzey1**

### CODE REVIEW

**Review by taylor13 — COMMENTED** [review]
The compare (diff) is against 01.00.27.  Shouldn't we be modifying 01.00.28?  Maybe it doesn't matter.  Please advise.  thanks.
Also, I just noticed that "vertices" has no attribute information.  We need to check on how vertices is used.   And the "variables" (i.e., not the "axes") in this file are longitude, latitude ....   and I wonder if these need to be "double" or not.  Need to check on this.

**Comment by mauzey1** [comment]
@taylor13 Should we commit 01.00.28 to the XML repo first?

**Comment by taylor13** [comment]
The main requirement, I think, is that users should continue to have access to older versions of the CMOR tables, and it looks like at https://github.com/PCMDI/cmip6-cmor-tables/releases they do have access to the version based on data request 01.00.28 .  I think we should also retain ability to reproduce those tables from Martin's original XMLs, so maybe we need to tag or release versions of  https://github.com/PCMDI/xml-cmor3-database each time Martin updates his stuff.  But I could be wrong about this.  What do you think?

**Comment by mauzey1** [comment]
@taylor13 I created a release for data request 01.00.28.  It's from the branch used to create the tables for the 6.4.28 release of cmip6-cmor-tables.

https://github.com/PCMDI/xml-cmor3-database/releases/tag/01.00.28

**Pull request closed without merging**
